// Labels reflect the current onboarding questionnaire. Unknown legacy fields remain visible.
export const fieldLabels: Record<string, string> = {
  "operatorName": "Operator or group name",
  "operatorFirstName": "Primary contact first name",
  "operatorLastName": "Last name",
  "operatorEmail": "Work email",
  "operatorRole": "Role",
  "propertyName": "Property name",
  "propertyCity": "City",
  "propertyCountry": "Country",
  "propertyType": "What type of property is this?",
  "totalRooms": "Total rooms",
  "totalUnits": "Total units",
  "propertyDescription": "What makes this property distinctive?",
  "guestTypes": "Who typically stays with you?",
  "guestPriorities": "What do guests care about most?",
  "reviewIssue": "What issue appears most often in reviews?",
  "seasonality": "Describe peak and quiet periods",
  "spaces": "Which spaces are available to guests?",
  "categoryOpportunities": "Which product categories could improve the guest experience?",
  "categoryRestrictions": "Are there any categories that are not appropriate?",
  "deliveryOwner": "Who receives product deliveries?",
  "placementOwner": "Who places products after room turnover?",
  "evidenceOwner": "Who captures fulfilment photos?",
  "operationsConfidence": "How confident are you that the team can complete a small task after every checkout?",
  "bookingPlatforms": "Which booking platforms do you use?",
  "pms": "Which PMS or management system do you use?",
  "reportingCapability": "Can you export a monthly stay or booking report?",
  "firstName": "First name",
  "lastName": "Last name",
  "email": "Work email",
  "mobile": "Mobile number",
  "jobTitle": "Job title",
  "onboardingRole": "What is your role in this onboarding?",
  "contact2Name": "Name",
  "contact2Email": "Work email",
  "contact2Role": "Role",
  "contact2Updates": "Should they receive IRL updates?",
  "brandName": "Brand name",
  "brandWebsite": "Brand website",
  "partOfGroup": "Is the brand part of a larger company or group?",
  "parentCompany": "Parent company or group name",
  "brandCountry": "Country",
  "brandCity": "City",
  "activeMarkets": "Which markets is the brand currently active in?",
  "brandPrimaryCategory": "What is the brand’s primary category?",
  "brandSecondaryCategories": "Does the brand also operate in another category?",
  "brandDescription": "How would you describe the brand in one sentence?",
  "qualities": "Which qualities are most central to the brand?",
  "salesChannels": "Where can customers currently buy the brand?",
  "productScope": "What would you like IRL to consider?",
  "productName": "Product or range name",
  "productWebpage": "Product webpage",
  "productCategory": "Pick the product category",
  "productSubcategory": "Product subcategory",
  "priceCurrency": "Currency",
  "priceMin": "Minimum retail price",
  "priceMax": "Maximum retail price",
  "variants": "Which variants should IRL consider?",
  "sameProductAvailability": "Is this product available through the same markets and channels listed for the brand?",
  "productMarkets": "Product-specific markets",
  "productChannels": "Product-specific channels",
  "product2Name": "Product or range name",
  "product2Category": "Product category",
  "product2Price": "Typical retail price or range",
  "audienceDescription": "Describe the priority audience you would most like IRL to reach",
  "audienceGeography": "Where is this audience based?",
  "ageGroups": "Which age groups are most relevant?",
  "lifeStages": "Which life stages are most relevant?",
  "decisionFactors": "What matters most when they choose this type of product?",
  "discoveryOpenness": "How open are they to trying an unfamiliar brand or product?",
  "audienceExclusions": "Is there anyone this product is not intended for?",
  "audienceEvidence": "How is this audience understanding informed?",
  "audienceNotes": "Is there anything else IRL should understand about this audience?",
  "secondaryAudienceDescription": "Describe the secondary audience",
  "secondaryAudienceGeography": "Where is this audience based?",
  "customerNeed": "What need or outcome is the customer looking for?",
  "needContext": "When is this need most relevant?",
  "currentAlternative": "What are customers currently using or doing instead?",
  "alternativeExplanation": "Optional explanation",
  "primaryBarrier": "What is the single biggest barrier to choosing this product?",
  "barrierReducers": "What would most help reduce that barrier?",
  "decisionNotes": "Is there anything else IRL should understand about this decision?",
  "marketingChannels": "Which channels currently play the biggest role in reaching this audience?",
  "irlOpportunity": "What is the main gap or opportunity you would like IRL to help address?",
  "guestUsageModel": "How would guests use the product?",
  "handlingRequirements": "Does the product require any special setup or handling?",
  "supplyCapability": "Could your team supply and replenish the product for an initial pilot?",
  "primarySuccessResult": "What is the single most important result IRL should support?",
  "successSignals": "Which signals would be most useful to see in reporting?",
  "complianceRequirements": "Are there any mandatory brand, safety or compliance requirements?",
  "messagingRequirements": "Are there any claims, words or messages IRL must use or avoid?",
  "associationRestrictions": "Are there any environments, categories or associations the brand should avoid?",
  "finalNotes": "Is there anything else IRL should know before we begin matching?"
};
export const fieldSections: Record<string, Record<string, string>> = {
  "brand": {
    "firstName": "team",
    "lastName": "team",
    "email": "team",
    "mobile": "team",
    "jobTitle": "team",
    "onboardingRole": "team",
    "additionalContactEnabled": "team",
    "contact2Name": "team",
    "contact2Email": "team",
    "contact2Role": "team",
    "contact2Updates": "team",
    "brandName": "brand",
    "brandWebsite": "brand",
    "partOfGroup": "brand",
    "parentCompany": "brand",
    "brandCountry": "brand",
    "brandCity": "brand",
    "activeMarkets": "brand",
    "brandPrimaryCategory": "brand",
    "brandSecondaryCategories": "brand",
    "brandDescription": "brand",
    "qualities": "brand",
    "salesChannels": "brand",
    "productScope": "product",
    "productName": "product",
    "productWebpage": "product",
    "productCategory": "product",
    "productSubcategory": "product",
    "priceCurrency": "product",
    "priceMin": "product",
    "priceMax": "product",
    "variants": "product",
    "sameProductAvailability": "product",
    "productMarkets": "product",
    "productChannels": "product",
    "additionalProductEnabled": "product",
    "product2Name": "product",
    "product2Category": "product",
    "product2Price": "product",
    "audienceDescription": "audience",
    "audienceGeography": "audience",
    "ageGroups": "audience",
    "lifeStages": "audience",
    "decisionFactors": "audience",
    "discoveryOpenness": "audience",
    "audienceExclusions": "audience",
    "audienceEvidence": "audience",
    "audienceNotes": "audience",
    "secondaryAudienceEnabled": "audience",
    "secondaryAudienceDescription": "audience",
    "secondaryAudienceGeography": "audience",
    "customerNeed": "need",
    "needContext": "need",
    "currentAlternative": "need",
    "alternativeExplanation": "need",
    "primaryBarrier": "need",
    "barrierReducers": "need",
    "decisionNotes": "need",
    "marketingChannels": "value",
    "irlOpportunity": "value",
    "guestUsageModel": "operations",
    "handlingRequirements": "operations",
    "supplyCapability": "operations",
    "primarySuccessResult": "success",
    "successSignals": "success",
    "complianceRequirements": "requirements",
    "messagingRequirements": "requirements",
    "associationRestrictions": "requirements",
    "finalNotes": "review",
    "profileConfirmed": "review"
  },
  "operator": {
    "operatorName": "organisation",
    "operatorFirstName": "organisation",
    "operatorLastName": "organisation",
    "operatorEmail": "organisation",
    "operatorRole": "organisation",
    "propertyName": "property",
    "propertyCity": "property",
    "propertyCountry": "property",
    "propertyType": "property",
    "totalRooms": "property",
    "totalUnits": "property",
    "propertyDescription": "property",
    "guestTypes": "guests",
    "guestPriorities": "guests",
    "reviewIssue": "guests",
    "seasonality": "guests",
    "spaces": "spaces",
    "categoryOpportunities": "spaces",
    "categoryRestrictions": "spaces",
    "deliveryOwner": "operations",
    "placementOwner": "operations",
    "evidenceOwner": "operations",
    "operationsConfidence": "operations",
    "bookingPlatforms": "data",
    "pms": "data",
    "reportingCapability": "data"
  }
};
export const sectionTitles: Record<string, Record<string, string>> = {
  "brand": {
    "team": "Your team",
    "brand": "About your brand",
    "product": "The product or range",
    "audience": "Who you want to reach",
    "need": "Customer need and barrier",
    "value": "How IRL should add value",
    "operations": "Making it work",
    "success": "What success looks like",
    "requirements": "Brand requirements",
    "review": "Review and submit"
  },
  "operator": {
    "organisation": "Your organisation",
    "property": "Your property",
    "guests": "Your guests",
    "spaces": "Spaces and experiences",
    "operations": "How it works",
    "data": "Data and systems",
    "review": "Review and submit"
  }
};
export const sectionOrder: Record<string, string[]> = {
  "brand": [
    "team",
    "brand",
    "product",
    "audience",
    "need",
    "value",
    "operations",
    "success",
    "requirements",
    "review"
  ],
  "operator": [
    "organisation",
    "property",
    "guests",
    "spaces",
    "operations",
    "data",
    "review"
  ]
};
