// Labels reflect the current onboarding questionnaire. Unknown legacy fields remain visible.
export const fieldLabels: Record<string, string> = {
  "operatorName": "Operator or group name",
  "operatorFirstName": "Primary contact first name",
  "operatorLastName": "Last name",
  "operatorEmail": "Work email",
  "operatorRole": "Role",
  "propertyName": "Property name",
  "propertyCity": "City",
  "propertyCountry": "Country",
  "propertyType": "What type of property is this?",
  "totalRooms": "Total rooms",
  "totalUnits": "Total units",
  "propertyDescription": "What makes this property distinctive?",
  "guestTypes": "Who typically stays with you?",
  "guestPriorities": "What do guests care about most?",
  "reviewIssue": "What issue appears most often in reviews?",
  "seasonality": "Describe peak and quiet periods",
  "spaces": "Which spaces are available to guests?",
  "categoryOpportunities": "Which product categories could improve the guest experience?",
  "categoryRestrictions": "Are there any categories that are not appropriate?",
  "deliveryOwner": "Who receives product deliveries?",
  "placementOwner": "Who places products after room turnover?",
  "evidenceOwner": "Who captures fulfilment photos?",
  "operationsConfidence": "How confident are you that the team can complete a small task after every checkout?",
  "bookingPlatforms": "Which booking platforms do you use?",
  "pms": "Which PMS or management system do you use?",
  "reportingCapability": "Can you export a monthly stay or booking report?",
  "firstName": "First name",
  "lastName": "Last name",
  "email": "Work email",
  "mobile": "Mobile number",
  "jobTitle": "Job title",
  "onboardingRole": "What is your role in this onboarding?",
  "counterpartFirstName": "Counterpart first name",
  "counterpartLastName": "Counterpart last name",
  "counterpartEmail": "Counterpart work email",
  "counterpartJobTitle": "Counterpart job title",
  "additionalContacts": "Additional contacts",
  "contact2Name": "Name",
  "contact2Email": "Work email",
  "contact2Role": "Role",
  "contact2Updates": "Should they receive IRL updates?",
  "brandName": "Brand name",
  "brandWebsite": "Brand website",
  "partOfGroup": "Is the brand part of a larger company or group?",
  "parentCompany": "Parent company or group name",
  "brandCountry": "Country",
  "brandCity": "City",
  "activeMarkets": "Which markets is the brand currently active in?",
  "brandPrimaryCategory": "What is the brand’s primary category?",
  "brandPrimaryCategoryOther": "Other primary category",
  "brandSecondaryCategories": "Does the brand also operate in another category?",
  "brandSecondaryCategoriesOther": "Other secondary category",
  "brandDescription": "How would you describe the brand in one sentence?",
  "brandDifferentiator": "What most sets your brand apart?",
  "brandValues": "What does your brand stand for?",
  "competitorLockouts": "Competitor brands or categories to avoid",
  "brandNeighbourhood": "Brands that feel at home in the ideal customer's bag",
  "qualities": "Which qualities are most central to the brand?",
  "salesChannels": "Where can customers currently buy the brand?",
  "salesChannelsOther": "Other sales channel",
  "productScope": "What would you like IRL to consider?",
  "productName": "Product or range name",
  "productWebpage": "Product webpage",
  "hasProductWebpage": "Does it have a product webpage?",
  "productCategory": "Product category",
  "productSubcategory": "Product subcategory",
  "productCategoryOther": "Other product category",
  "productSubcategoryOther": "Other product subcategory",
  "priceCurrency": "Currency",
  "priceMin": "Minimum retail price",
  "priceMax": "Maximum retail price",
  "variants": "Are there any variants you want IRL to focus on?",
  "sameProductAvailability": "Is this product available through the same markets and channels listed for the brand?",
  "productMarkets": "Product-specific markets",
  "productChannels": "Product-specific channels",
  "productChannelsOther": "Other product-specific channel",
  "internationalShipping": "Do you ship internationally?",
  "internationalShippingRegions": "International shipping regions",
  "legalSafetyCompliance": "Legal, safety or compliance information",
  "additionalProducts": "Additional products or ranges",
  "product2Name": "Product or range name",
  "product2Category": "Product category",
  "product2Price": "Typical retail price or range",
  "audienceDescription": "Describe the priority audience beyond their basic demographics",
  "audienceGeography": "Where is this audience based?",
  "audienceGeographyDetail": "Audience countries or regions",
  "ageGroups": "Which age groups are most relevant?",
  "lifeStages": "Which life stages are most relevant?",
  "lifeStagesOther": "Other life stage",
  "spendingPower": "Income or spending-power bands",
  "travelPurpose": "Typical customer travel purpose",
  "discoveryChannels": "Where this audience typically discovers products like yours",
  "discoveryChannelsOther": "Other discovery channel",
  "decisionFactors": "What matters most when they choose this type of product?",
  "decisionFactorsOther": "Other decision factor",
  "discoveryOpenness": "How open are they to trying an unfamiliar brand or product?",
  "audienceExclusions": "Is there anyone this product is not intended for?",
  "audienceEvidence": "How is this audience understanding informed?",
  "audienceEvidenceOther": "Other audience evidence",
  "secondaryAudienceEvidence": "How the secondary audience is known",
  "secondaryAudienceEvidenceOther": "Other secondary audience evidence",
  "secondaryAgeGroups": "Secondary audience age groups",
  "secondaryLifeStages": "Secondary audience life stages",
  "secondaryLifeStagesOther": "Other secondary audience life stage",
  "secondarySpendingPower": "Secondary audience spending power",
  "secondaryTravelPurpose": "Secondary audience travel purpose",
  "secondaryDiscoveryChannels": "Secondary audience discovery channels",
  "secondaryDiscoveryChannelsOther": "Other secondary discovery channel",
  "secondaryDecisionFactors": "Secondary audience ranked priorities",
  "secondaryDecisionFactorsOther": "Other secondary decision factor",
  "secondaryDiscoveryOpenness": "Secondary audience openness",
  "secondaryAudienceExclusions": "Secondary audience exclusions",
  "secondaryAudienceNotes": "Additional secondary audience information",
  "audienceNotes": "Is there anything else IRL should understand about this audience?",
  "secondaryAudienceDescription": "Describe the secondary audience",
  "secondaryAudienceGeography": "Where is this audience based?",
  "secondaryAudienceGeographyDetail": "Secondary audience countries or regions",
  "customerNeed": "What need or outcome is the customer looking for?",
  "customerOutcome": "What outcome is the customer looking for?",
  "customerOutcomeOther": "Other customer outcome",
  "customerOutcomeDetail": "Customer outcome detail",
  "needContext": "When is this need most relevant?",
  "currentAlternative": "What are customers currently using or doing instead?",
  "alternativeExplanation": "Optional explanation",
  "primaryBarrier": "What is the single biggest barrier to choosing this product?",
  "barrierReducers": "What do you believe would most help a customer choose your product?",
  "decisionNotes": "Is there anything else IRL should understand about this decision?",
  "marketingChannels": "Which channels does your team currently use to reach this audience?",
  "marketingChannelsOther": "Other marketing channel",
  "marketingChannelRank": "Most-used marketing channels in ranked order",
  "measuredAcquisitionChannel": "Channel driving the most measurable acquisition or sales",
  "paidMarketing": "Current paid marketing activity",
  "experientialHistory": "Previous real-world or experiential activity",
  "experientialHistoryOther": "Other experiential activity",
  "experientialEffectiveness": "Effectiveness of previous experiential activity",
  "experientialEvidence": "Evidence for experiential effectiveness",
  "irlOpportunity": "What is the main gap or opportunity you would like IRL to help address?",
  "guestUsageModel": "How would guests use the product?",
  "brandSuggestedPlacements": "Where guests could use or experience the product",
  "brandSuggestedPlacementsOther": "Other suggested placement",
  "handlingRequirements": "Does the product require any special setup or handling?",
  "handlingRequirementsOther": "Other handling requirement",
  "supplyCapability": "Could you supply product for an initial IRL experience?",
  "initialSupplyLimit": "Practical initial supply limit",
  "primarySuccessResult": "What is the single most important result IRL should support?",
  "successSignals": "Which signals would be most useful to see in reporting?",
  "successSignalsOther": "Other reporting signal",
  "complianceRequirements": "Are there any mandatory brand, safety or compliance requirements?",
  "messagingRequirements": "Are there any claims, words or messages IRL must use or avoid?",
  "associationRestrictions": "Are there any environments, categories or associations the brand should avoid?",
  "finalNotes": "Is there anything else IRL should know before we begin matching?"
};
export const fieldSections: Record<string, Record<string, string>> = {
  "brand": {
    "firstName": "team",
    "lastName": "team",
    "email": "team",
    "mobile": "team",
    "jobTitle": "team",
    "onboardingRole": "team",
    "counterpartFirstName": "team",
    "counterpartLastName": "team",
    "counterpartEmail": "team",
    "counterpartJobTitle": "team",
    "additionalContacts": "team",
    "additionalContactEnabled": "team",
    "contact2Name": "team",
    "contact2Email": "team",
    "contact2Role": "team",
    "contact2Updates": "team",
    "brandName": "brand",
    "brandWebsite": "brand",
    "partOfGroup": "brand",
    "parentCompany": "brand",
    "brandCountry": "brand",
    "brandCity": "brand",
    "activeMarkets": "brand",
    "brandPrimaryCategory": "brand",
    "brandPrimaryCategoryOther": "brand",
    "brandSecondaryCategories": "brand",
    "brandSecondaryCategoriesOther": "brand",
    "brandDescription": "brand",
    "brandDifferentiator": "brand",
    "brandValues": "brand",
    "competitorLockouts": "brand",
    "brandNeighbourhood": "brand",
    "qualities": "brand",
    "salesChannels": "brand",
    "salesChannelsOther": "brand",
    "productScope": "product",
    "productName": "product",
    "productWebpage": "product",
    "hasProductWebpage": "product",
    "productCategory": "product",
    "productSubcategory": "product",
    "productCategoryOther": "product",
    "productSubcategoryOther": "product",
    "priceCurrency": "product",
    "priceMin": "product",
    "priceMax": "product",
    "variants": "product",
    "sameProductAvailability": "product",
    "productMarkets": "product",
    "productChannels": "product",
    "productChannelsOther": "product",
    "internationalShipping": "product",
    "internationalShippingRegions": "product",
    "legalSafetyCompliance": "product",
    "additionalProducts": "product",
    "additionalProductEnabled": "product",
    "product2Name": "product",
    "product2Category": "product",
    "product2Price": "product",
    "audienceDescription": "audience",
    "audienceGeography": "audience",
    "audienceGeographyDetail": "audience",
    "ageGroups": "audience",
    "lifeStages": "audience",
    "lifeStagesOther": "audience",
    "spendingPower": "audience",
    "travelPurpose": "audience",
    "discoveryChannels": "audience",
    "discoveryChannelsOther": "audience",
    "decisionFactors": "audience",
    "decisionFactorsOther": "audience",
    "discoveryOpenness": "audience",
    "audienceExclusions": "audience",
    "audienceEvidence": "audience",
    "audienceEvidenceOther": "audience",
    "audienceNotes": "audience",
    "secondaryAudienceEnabled": "audience",
    "secondaryAudienceDescription": "audience",
    "secondaryAudienceGeography": "audience",
    "secondaryAudienceGeographyDetail": "audience",
    "secondaryAudienceEvidence": "audience",
    "secondaryAudienceEvidenceOther": "audience",
    "secondaryAgeGroups": "audience",
    "secondaryLifeStages": "audience",
    "secondaryLifeStagesOther": "audience",
    "secondarySpendingPower": "audience",
    "secondaryTravelPurpose": "audience",
    "secondaryDiscoveryChannels": "audience",
    "secondaryDiscoveryChannelsOther": "audience",
    "secondaryDecisionFactors": "audience",
    "secondaryDecisionFactorsOther": "audience",
    "secondaryDiscoveryOpenness": "audience",
    "secondaryAudienceExclusions": "audience",
    "secondaryAudienceNotes": "audience",
    "customerNeed": "need",
    "customerOutcome": "need",
    "customerOutcomeOther": "need",
    "customerOutcomeDetail": "need",
    "needContext": "need",
    "currentAlternative": "need",
    "alternativeExplanation": "need",
    "primaryBarrier": "need",
    "barrierReducers": "need",
    "decisionNotes": "need",
    "marketingChannels": "value-success",
    "marketingChannelsOther": "value-success",
    "marketingChannelRank": "value-success",
    "measuredAcquisitionChannel": "value-success",
    "paidMarketing": "value-success",
    "experientialHistory": "value-success",
    "experientialHistoryOther": "value-success",
    "experientialEffectiveness": "value-success",
    "experientialEvidence": "value-success",
    "irlOpportunity": "value-success",
    "guestUsageModel": "operations",
    "brandSuggestedPlacements": "operations",
    "brandSuggestedPlacementsOther": "operations",
    "handlingRequirements": "operations",
    "handlingRequirementsOther": "operations",
    "supplyCapability": "operations",
    "initialSupplyLimit": "operations",
    "primarySuccessResult": "value-success",
    "successSignals": "value-success",
    "successSignalsOther": "value-success",
    "complianceRequirements": "requirements",
    "messagingRequirements": "requirements",
    "associationRestrictions": "requirements",
    "finalNotes": "review",
    "profileConfirmed": "review"
  },
  "operator": {
    "operatorName": "organisation",
    "operatorFirstName": "organisation",
    "operatorLastName": "organisation",
    "operatorEmail": "organisation",
    "operatorRole": "organisation",
    "propertyName": "property",
    "propertyCity": "property",
    "propertyCountry": "property",
    "propertyType": "property",
    "totalRooms": "property",
    "totalUnits": "property",
    "propertyDescription": "property",
    "guestTypes": "guests",
    "guestPriorities": "guests",
    "reviewIssue": "guests",
    "seasonality": "guests",
    "spaces": "spaces",
    "categoryOpportunities": "spaces",
    "categoryRestrictions": "spaces",
    "deliveryOwner": "operations",
    "placementOwner": "operations",
    "evidenceOwner": "operations",
    "operationsConfidence": "operations",
    "bookingPlatforms": "data",
    "pms": "data",
    "reportingCapability": "data"
  }
};
export const sectionTitles: Record<string, Record<string, string>> = {
  "brand": {
    "team": "Your team",
    "brand": "About your brand",
    "product": "The product or range",
    "audience": "Who you want to reach",
    "need": "Customer need and barrier",
    "value": "How IRL should add value",
    "value-success": "How IRL should add value and what success looks like",
    "operations": "Making it work",
    "success": "What success looks like",
    "requirements": "Brand requirements",
    "review": "Review and submit"
  },
  "operator": {
    "organisation": "Your organisation",
    "property": "Your property",
    "guests": "Your guests",
    "spaces": "Spaces and experiences",
    "operations": "How it works",
    "data": "Data and systems",
    "review": "Review and submit"
  }
};
export const sectionOrder: Record<string, string[]> = {
  "brand": [
    "team",
    "brand",
    "product",
    "audience",
    "need",
    "value-success",
    "operations",
    "value",
    "success",
    "requirements",
    "review"
  ],
  "operator": [
    "organisation",
    "property",
    "guests",
    "spaces",
    "operations",
    "data",
    "review"
  ]
};
